[bin/g2h,bin/h2g] Better error checking, use moz env and util.sh

diff --git a/bin/g2h b/bin/g2h
--- a/bin/g2h
+++ b/bin/g2h
@@ -1,21 +1,25 @@
 #!/bin/bash
 
-g=$1
-r="$(basename "$PWD")"
+set -e
+
+. "$(dirname "$(readlink -f "$0")")"/lib/util.sh
+parse_args g2h '' '' "$@"
+g="$(get_arg 1)"
+([ ! -z "$g" ] && [[ $(num_args) -eq 1 ]]) || die "Expect a single argument"
+
+if [[ ! "$g" =~ ^[a-Z0-9]{7,40}$ ]]; then
+  if [ -z "$MOZTREE" ]; then
+    die "This doesn't look like a hash, and we have no moz config to parse it"
+  fi
+  cd "$MOZPATH/$MOZTREE"
+  go="$(git rev-parse "$g")"
+  [ ! -z "$go" ] || die "Couldn't parse '$g' into any git has in $MOZTREE"
+  g="$go"
+fi
 
 map="$MOZPATH/hg-git-map/hg-git-mapfile"
-g=$(git rev-parse "$g")
+h="$(grep -E -m 1 ^$g "$map" | cut -d ' ' -f 2)"
 
-if [ -z "$g" ]; then
-    echo >&2 "!! Could not find git commit"
-    exit 1
-fi
-
-h=$(cat "$map" | grep -m 1 $g | cut -d ' ' -f 2)
-
-if [ -z "$h" ]; then
-    echo >&2 "!! Not found"
-    exit 1
-fi
+[ ! -z "$h" ] || die "git hash $g not found in map"
 
 echo $h
diff --git a/bin/h2g b/bin/h2g
--- a/bin/h2g
+++ b/bin/h2g
@@ -1,25 +1,25 @@
 #!/bin/bash
 
-h=$1
+set -e
+
+. "$(dirname "$(readlink -f "$0")")"/lib/util.sh
+parse_args h2g '' '' "$@"
+h="$(get_arg 1)"
+([ ! -z "$h" ] && [[ $(num_args) -eq 1 ]]) || die "Expect a single argument"
 
 if [ -d .hg ]; then
-   h=$(hg log -r "$h" --template {node})
+   ho=$(hg log -r "$h" --template {node})
+   [ ! -z "$h" ] || die "Could not map \"$h\" to an hg hash"
+   h="$ho"
+elif [[ ! "$h" =~ ^[a-Z0-9]{12,40}$ ]]; then
+  eerr "This doesn't look like a Hg hash, and the current directory is not an"
+  die  "Hg repository to attempt to resolve it to one"
 fi
 
 map="$MOZPATH/hg-git-map/hg-git-mapfile"
 
-r="$(basename "$PWD")"
+g=$(grep -E -m 1 " $h[a-z0-9]*$" "$map" | cut -d ' ' -f 1)
 
-if [ -z "$h" ]; then
-    echo >&2 "!! Could not find hg commit"
-    exit 1
-fi
-
-g=$(cat "$map" | grep -m 1 $h | cut -d ' ' -f 1)
-
-if [ -z "$g" ]; then
-    echo >&2 "!! No matching git commit"
-    exit 1
-fi
+[ ! -z "$g" ] || die No matching git commit
 
 echo $g
