[bin/han] Propagate error if man fails

diff --git a/bin/han b/bin/han
--- a/bin/han
+++ b/bin/han
@@ -3,17 +3,26 @@
 set -e
 . ~/bin/lib/util.sh
 
-cleanup() { [[ -z $tmp ]] || rm -f "$tmp"; }
+cleanup() {
+  [[ -z $tmp ]] || rm -f "$tmp";
+  [[ -z $errtmp ]] || rm -f "$errtmp";
+}
 trap cleanup EXIT
 
 tmp="$(mktemp --tmpdir han_XXXX.htm)"
+errtmp="$(mktemp --tmpdir han_stderr_XXXX.log)"
 
-cmd man -Thtml "$@" 2>/dev/null > "$tmp"
+# Eat stderr because it spews a bunch of troff HTML debugging output for some
+# reason, but display it if it actually fails.
+showcmd man -Thtml "$@"
+if ! man -Thtml "$@" 2> "$errtmp" > "$tmp"; then
+  die "$(cat "$errtmp")"
+fi
 cmd xdg-open "$tmp"
 
 # xdg-open seems to do the right thing and wait for the browser... or maybe it's
 # just slow? A more-proper script would spin up a small python http that dies
 # after the first request.
 ( ( sleep 5 && rm -f "$tmp" ) & )
-# If that worked don't trigger exit clenaup
-trap - EXIT
+# If that worked don't trigger exit cleanup
+unset tmp
